<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql = "INSERT INTO `tbl_products` (`id`, `contract_id`, `producttype_code`, `name`, `description`, `count`, `dai`, `rong`, `cao`, `elements`, `created_at`, `updated_at`) VALUES
(1, 5, 'SACH', 'Cum est est facilis.', 'Vero facere consequatur totam est est neque. Est tempore illum aut aliquid cupiditate.', 374, '205', '316', '490', NULL, NULL, NULL),
(2, 4, 'SACH', 'Qui aut et neque quia.', 'Veniam aliquam molestiae sequi provident. A autem dolore deserunt. Numquam qui id laboriosam et.', 222, '245', '402', '305', NULL, NULL, NULL),
(3, 4, 'SACH', 'Ut rerum cumque ab a.', 'Repellat quis autem eos sapiente nihil enim laudantium. Ullam ratione quo consequatur ut at.', 355, '386', '500', '174', NULL, NULL, NULL),
(4, 0, 'SACH', 'Sit quis vero ea quam.', 'Nisi quia magnam sit quo ad. Ut velit alias in autem. Voluptas enim nam vel aut sit deserunt.', 179, '232', '386', '466', NULL, NULL, NULL),
(5, 0, 'SACH', 'Ut sit at sunt.', 'Debitis commodi ipsam nobis sequi sed cumque. Pariatur sed enim quia facilis sequi.', 288, '337', '442', '340', NULL, NULL, NULL),
(6, 9, 'SACH', 'Quo ea quis et soluta.', 'Eos impedit corporis dolorem necessitatibus. Quasi esse quia dicta et. Cum est aperiam odit iste.', 465, '148', '384', '323', NULL, NULL, NULL),
(7, 2, 'SACH', 'Rem qui est dolore.', 'Quis aliquam quo tenetur. Et omnis velit quaerat velit quia sunt laudantium veniam.', 273, '386', '477', '404', NULL, NULL, NULL),
(8, 0, 'SACH', 'Sed iure consequatur ea.', 'A possimus quod nesciunt consequatur ipsa. Magnam et qui odio voluptates illo quia nobis.', 284, '105', '489', '326', NULL, NULL, NULL),
(9, 3, 'SACH', 'Qui ut ut sunt est.', 'Sapiente quia dolor sit quam corporis nihil iure. Enim ducimus porro voluptatem provident aut.', 195, '101', '229', '118', NULL, NULL, NULL),
(10, 6, 'SACH', 'Eaque et qui quas.', 'Neque in totam quia quasi. Iure sunt molestias sapiente velit ad.', 279, '100', '130', '310', NULL, NULL, NULL),
(11, 4, 'SACH', 'Est ut et quasi eos est.', 'Voluptates sapiente molestiae aliquam. Tenetur ab fugit et est tenetur. Id nostrum eos distinctio.', 428, '187', '109', '278', NULL, NULL, NULL),
(12, 5, 'SACH', 'Dolor quidem id veniam.', 'Repellendus id commodi dolorem recusandae. Aspernatur molestiae voluptates ipsam pariatur et et.', 429, '321', '376', '198', NULL, NULL, NULL),
(13, 8, 'SACH', 'Et illo porro voluptas.', 'Quia eos sint et est tempora eveniet. Et vero et odit consectetur. Rerum corporis et ipsam unde.', 132, '387', '416', '212', NULL, NULL, NULL),
(14, 0, 'SACH', 'Fuga labore sed nobis.', 'Cum qui omnis sint maiores. Ea possimus qui aperiam et et voluptatem.', 352, '240', '229', '301', NULL, NULL, NULL),
(15, 0, 'SACH', 'Ipsam atque quia id.', 'Atque nobis atque magni velit sequi rerum. Et earum quos et. Est eos voluptate blanditiis eligendi.', 357, '179', '435', '487', NULL, NULL, NULL),
(16, 9, 'SACH', 'Atque aut ipsam dolores.', 'Omnis doloremque tenetur est sed et sit consequatur. Aut quia voluptas autem hic deleniti facere.', 401, '117', '133', '419', NULL, NULL, NULL),
(17, 3, 'SACH', 'Quia odit id omnis.', 'Voluptatem harum sit dolores est omnis exercitationem et ipsum. Molestiae est vero sunt nobis at.', 337, '282', '340', '408', NULL, NULL, NULL),
(18, 4, 'SACH', 'Dolores a in omnis odio.', 'Eum error velit veniam dolorem aut. Voluptatem quae doloremque in. Aut sit animi earum itaque.', 370, '103', '267', '136', NULL, NULL, NULL),
(19, 9, 'SACH', 'Et dolore pariatur rem.', 'Quo aliquid qui ipsum ea. Aspernatur quia et ab blanditiis. Ut quia ut aut.', 197, '148', '291', '317', NULL, NULL, NULL),
(20, 0, 'SACH', 'Porro ut rerum ex iure.', 'Animi ea reprehenderit magnam placeat. Deserunt blanditiis enim nihil est eum.', 188, '132', '450', '327', NULL, NULL, NULL),
(21, 6, 'SACH', 'Ex ipsum quia magnam.', 'Quod et quaerat et. Tenetur quisquam nam qui eligendi cupiditate.', 448, '272', '338', '293', NULL, NULL, NULL),
(22, 3, 'SACH', 'Eos vel magni in.', 'Cupiditate sint odit nobis aperiam nihil numquam. Illo illum esse id qui cumque.', 222, '228', '434', '252', NULL, NULL, NULL),
(23, 1, 'SACH', 'Deserunt itaque et modi.', 'Harum numquam itaque delectus nihil itaque laudantium. Unde praesentium sed fugiat.', 287, '483', '315', '455', NULL, NULL, NULL),
(24, 2, 'SACH', 'Modi magnam magnam sit.', 'In dolorum excepturi et minima. Nesciunt nesciunt voluptates sed eum. Est omnis quia quos.', 378, '403', '212', '259', NULL, NULL, NULL),
(25, 4, 'SACH', 'Voluptas unde id enim.', 'Est est enim a est. Necessitatibus omnis illo nam.', 302, '246', '147', '456', NULL, NULL, NULL),
(26, 8, 'SACH', 'Amet esse neque aliquid.', 'Illo aut sit unde deserunt eaque fugiat. In harum ex voluptatibus qui reprehenderit aut.', 396, '152', '314', '486', NULL, NULL, NULL),
(27, 5, 'SACH', 'Eius aut est dolorum.', 'Alias aut est quam dolor. Inventore ut et soluta et. Ea aut voluptate doloribus.', 364, '168', '144', '189', NULL, NULL, NULL),
(28, 4, 'SACH', 'Quo totam vel doloribus.', 'Minus soluta officiis quaerat facere libero. Facilis magnam voluptas qui ratione.', 156, '366', '107', '353', NULL, NULL, NULL),
(29, 3, 'SACH', 'Aliquid non sit ea.', 'Qui fugit debitis ratione maxime. Qui aut omnis ipsa et. Debitis omnis incidunt necessitatibus.', 336, '292', '105', '484', NULL, NULL, NULL),
(30, 3, 'SACH', 'Labore ea ab est.', 'Ad architecto ea quo ut. Eius unde vel rerum ex dignissimos possimus assumenda.', 378, '414', '498', '474', NULL, NULL, NULL),
(31, 2, 'SACH', 'Quo ut sed quis iusto.', 'Rem quibusdam quos quos facere sit. Sint rerum placeat voluptatem rerum.', 365, '395', '417', '207', NULL, NULL, NULL),
(32, 9, 'SACH', 'Et aliquam sit magni.', 'Vel perferendis aut est neque. Assumenda explicabo ab et molestias ut.', 113, '459', '225', '146', NULL, NULL, NULL),
(33, 2, 'SACH', 'Adipisci in dolore sunt.', 'Voluptates at repellat est rem rerum. Ad natus et magnam quo ipsam. Quis voluptatibus et ut.', 388, '296', '351', '163', NULL, NULL, NULL),
(34, 2, 'SACH', 'Minima nemo fugit sed.', 'Et culpa dolores fugiat quo et. Eius fugit ut distinctio cumque quo.', 256, '149', '170', '456', NULL, NULL, NULL),
(35, 1, 'SACH', 'Ut nobis qui odit.', 'Explicabo dolore consequatur esse aut ullam. Omnis maiores perspiciatis vero.', 428, '148', '370', '196', NULL, NULL, NULL),
(36, 4, 'SACH', 'Et libero sequi animi.', 'Error eligendi velit hic hic magni. Neque et commodi sunt doloribus ab.', 235, '120', '451', '176', NULL, NULL, NULL),
(37, 7, 'SACH', 'Eveniet saepe in qui.', 'Animi nam hic eos minus quo. Non quod tempore quod laudantium distinctio.', 496, '346', '421', '284', NULL, NULL, NULL),
(38, 10, 'SACH', 'Hic et qui aut fugiat.', 'Nihil expedita molestias ullam minus explicabo assumenda rem. Voluptatem atque doloremque unde.', 318, '296', '321', '468', NULL, NULL, NULL),
(39, 2, 'SACH', 'Suscipit in ratione et.', 'Incidunt officia sunt aut ad aut. Animi cumque porro maxime totam voluptas eos officia.', 490, '216', '240', '444', NULL, NULL, NULL),
(40, 5, 'SACH', 'A eos dicta et nam ut.', 'Suscipit sit qui ut voluptas totam sint nesciunt beatae. Exercitationem cumque debitis deserunt et.', 309, '187', '473', '380', NULL, NULL, NULL),
(41, 6, 'SACH', 'In ut et minima sequi.', 'Sed repudiandae beatae perspiciatis omnis. Dolore maxime natus et illum dolores vel cupiditate.', 496, '329', '453', '231', NULL, NULL, NULL),
(42, 6, 'SACH', 'Eius et earum excepturi.', 'Est est soluta in. Eum quia eius in beatae in. Et eum nemo eveniet iste.', 250, '393', '136', '348', NULL, NULL, NULL),
(43, 4, 'SACH', 'Nam aperiam in hic.', 'Recusandae ab animi rerum provident quibusdam. Nostrum quasi est voluptate vel.', 288, '388', '467', '237', NULL, NULL, NULL),
(44, 8, 'SACH', 'Ut quae qui eius.', 'Ab vel impedit quae cupiditate non quo. Quia quo dolorum debitis quae eligendi ducimus non.', 322, '498', '178', '496', NULL, NULL, NULL),
(45, 4, 'SACH', 'Sit sed rem ea dolorem.', 'Dolor delectus aut sed dolores. Explicabo voluptas qui voluptates. Voluptatem officiis aut enim.', 427, '334', '383', '393', NULL, NULL, NULL),
(46, 9, 'SACH', 'Et impedit et ullam.', 'Rerum nihil aut accusamus modi quasi. Nulla ut quaerat explicabo qui.', 342, '175', '203', '133', NULL, NULL, NULL),
(47, 9, 'SACH', 'Ut quia est aut nostrum.', 'Voluptatem praesentium eaque libero voluptates molestiae et. Iure ullam voluptatem est nesciunt.', 161, '248', '487', '264', NULL, NULL, NULL),
(48, 8, 'SACH', 'Aut quia quo ipsam ipsa.', 'Qui id et ex ea. Vel corrupti at eveniet veniam. Non et cum est aut dolorem possimus.', 464, '288', '455', '461', NULL, NULL, NULL),
(49, 2, 'SACH', 'Rerum animi non ipsam.', 'Dicta a quisquam et. Optio amet illo non. Incidunt at enim dolorum molestiae.', 126, '247', '350', '157', NULL, NULL, NULL),
(50, 7, 'SACH', 'Tenetur minus quia sed.', 'Sed qui dolorem quia quia. Voluptatem quaerat totam laborum sequi.', 279, '383', '110', '463', NULL, NULL, NULL),
(51, 2, 'SACH', 'In autem non qui est.', 'Itaque est et molestiae nemo voluptatem. Sequi nihil eveniet id non temporibus voluptas.', 245, '386', '336', '213', NULL, NULL, NULL),
(52, 3, 'SACH', 'Et placeat quod nisi.', 'Id tempore possimus vitae omnis necessitatibus ipsum. Odit ut ut ut. Unde debitis ut fugit sit.', 319, '196', '390', '413', NULL, NULL, NULL),
(53, 4, 'SACH', 'Unde ducimus enim quos.', 'Et eius totam beatae provident optio. Hic accusamus corrupti fugiat cupiditate.', 431, '156', '292', '312', NULL, NULL, NULL),
(54, 8, 'SACH', 'Voluptate quo porro sit.', 'Voluptates sint culpa rem nesciunt. Necessitatibus dolorem est sint incidunt.', 350, '352', '446', '171', NULL, NULL, NULL),
(55, 8, 'SACH', 'A sed architecto magnam.', 'Tempora velit natus at numquam. Fugit earum quos aperiam molestiae. Sunt incidunt vitae ea.', 480, '389', '254', '370', NULL, NULL, NULL),
(56, 7, 'SACH', 'Et at in nam nisi quod.', 'Dicta quas praesentium animi qui. Nemo magni consequatur illo esse. Ex aut et sunt et ut.', 478, '260', '471', '288', NULL, NULL, NULL),
(57, 9, 'SACH', 'Sequi illum libero eos.', 'Est debitis eum totam non delectus consequatur. Amet possimus laudantium qui.', 378, '349', '345', '243', NULL, NULL, NULL),
(58, 2, 'SACH', 'Quia ex quis a neque.', 'Qui consectetur et explicabo inventore eligendi quia. Laudantium dicta beatae similique.', 242, '420', '395', '299', NULL, NULL, NULL),
(59, 2, 'SACH', 'Quo dolor ad qui ex.', 'Sapiente quasi similique aut consequatur. Quod fugiat dolores quos ducimus nulla voluptatem.', 199, '444', '277', '423', NULL, NULL, NULL),
(60, 7, 'SACH', 'Ipsum rerum quo ut eum.', 'Soluta cupiditate ratione ipsum itaque quasi aut. Libero earum praesentium cumque voluptatem.', 125, '317', '185', '226', NULL, NULL, NULL),
(61, 2, 'SACH', 'Est at magnam et quia.', 'Qui illum sapiente nihil quasi vitae. Nihil in omnis voluptates.', 406, '113', '448', '340', NULL, NULL, NULL),
(62, 6, 'SACH', 'Qui quo quidem fugiat.', 'Dolorum iusto ut odio nobis. Nisi pariatur pariatur eius qui. Dignissimos quos et animi est et.', 243, '325', '147', '482', NULL, NULL, NULL),
(63, 8, 'SACH', 'Est et aut dolores.', 'Quod perferendis rerum aut non. Amet delectus ut velit eveniet. Voluptatem iure iste sed.', 144, '138', '243', '260', NULL, NULL, NULL),
(64, 8, 'SACH', 'Fugit itaque maxime ea.', 'Cumque illo quos ut nemo voluptate. Laborum fuga hic reprehenderit. Sed dignissimos sed nam ut.', 250, '404', '422', '163', NULL, NULL, NULL),
(65, 3, 'SACH', 'Eum dolorum nulla ut.', 'Corporis hic officia illum dolores. Saepe maxime pariatur veritatis maiores unde dolor.', 352, '135', '337', '389', NULL, NULL, NULL),
(66, 10, 'SACH', 'Facere sit quia hic.', 'Officia quaerat officiis aperiam itaque nisi. Sit iure et voluptatem rerum aperiam.', 440, '404', '489', '157', NULL, NULL, NULL),
(67, 1, 'SACH', 'Veniam qui cumque optio.', 'Ipsam est animi nesciunt. Nisi necessitatibus rerum corporis est qui qui.', 451, '461', '189', '368', NULL, NULL, NULL),
(68, 7, 'SACH', 'Aut ad nulla iure quis.', 'Nihil enim rem dicta. Suscipit iure consequatur non harum iste. Atque et velit id veniam.', 441, '359', '266', '236', NULL, NULL, NULL),
(69, 7, 'SACH', 'Ipsa aut aut eius quo.', 'Vel autem ea id sed aut distinctio voluptate. Ut a et est. Ut vel non facilis cum.', 253, '104', '350', '377', NULL, NULL, NULL),
(70, 9, 'SACH', 'Enim quos dolorum ipsam.', 'Ut similique sed amet ex quia ab autem ab. Et sint nihil non natus. Harum libero enim libero rerum.', 320, '395', '408', '163', NULL, NULL, NULL),
(71, 6, 'SACH', 'Qui voluptas est cumque.', 'Voluptas quidem ut voluptatem suscipit alias quis quia. Totam voluptas laudantium quia consequatur.', 256, '197', '354', '234', NULL, NULL, NULL),
(72, 8, 'SACH', 'Ea et sunt omnis omnis.', 'Culpa omnis magni esse perferendis. Sed eius et dolore sapiente ut laudantium aperiam temporibus.', 484, '220', '206', '385', NULL, NULL, NULL),
(73, 2, 'SACH', 'Omnis est omnis et.', 'Voluptatem sint dolorum quia voluptatem temporibus. Nemo non facilis deleniti quibusdam.', 347, '307', '225', '493', NULL, NULL, NULL),
(74, 6, 'SACH', 'Sed et quo in quaerat.', 'Aut repellendus aut sit. Aliquam impedit ea quis expedita nulla ut consequatur.', 372, '234', '292', '337', NULL, NULL, NULL),
(75, 9, 'SACH', 'Quo pariatur quo soluta.', 'Provident quo modi voluptates cumque. Sunt magnam consequuntur repellat commodi et voluptatem.', 499, '337', '375', '346', NULL, NULL, NULL),
(76, 0, 'SACH', 'Et blanditiis ut nemo.', 'Minus id quas omnis. Asperiores non voluptatem illum rerum labore in mollitia.', 366, '223', '130', '344', NULL, NULL, NULL),
(77, 5, 'SACH', 'In omnis est et.', 'Ipsam aut consectetur doloribus saepe quae. Fugiat laudantium magni voluptatem vero.', 272, '430', '300', '324', NULL, NULL, NULL),
(78, 5, 'SACH', 'Nam in at cum nam.', 'Molestias non modi molestias. Illum nemo quasi saepe corporis fugiat optio.', 482, '461', '328', '316', NULL, NULL, NULL),
(79, 0, 'SACH', 'Nam non earum sunt.', 'Officiis nostrum voluptate cum omnis qui esse. Repellendus qui aut in optio.', 315, '467', '488', '192', NULL, NULL, NULL),
(80, 6, 'SACH', 'Aut nihil rerum ex qui.', 'Omnis consequuntur explicabo qui ut eaque et. Cumque saepe nesciunt sed vel et ab.', 275, '408', '126', '453', NULL, NULL, NULL),
(81, 5, 'SACH', 'Fuga dolore et aut.', 'Beatae quis rerum autem tenetur. Cum exercitationem similique quia consequatur alias sequi.', 265, '362', '311', '457', NULL, NULL, NULL),
(82, 9, 'SACH', 'Et quis dolorem id.', 'Eum qui non vel nobis. Mollitia qui et voluptatem ipsa. Esse numquam tempora nemo et rerum.', 338, '212', '104', '339', NULL, NULL, NULL),
(83, 10, 'SACH', 'Et est unde fugit quia.', 'Totam autem natus sequi ab quia. Quia unde dolore ex tempore voluptas.', 243, '373', '331', '259', NULL, NULL, NULL),
(84, 5, 'SACH', 'Possimus qui eum rerum.', 'Non cumque minima ratione dolor. Quis et aut consequatur et aut ut.', 200, '210', '480', '448', NULL, NULL, NULL),
(85, 6, 'SACH', 'Mollitia earum sed quia.', 'Maxime quaerat velit quia et. Quam dolorem vel dolor sed voluptatibus.', 363, '190', '196', '480', NULL, NULL, NULL),
(86, 2, 'SACH', 'Et qui laborum sequi at.', 'Voluptas fuga fuga nostrum et. Aut nobis tempore in ex aut natus. Qui odio in autem.', 228, '425', '207', '442', NULL, NULL, NULL),
(87, 9, 'SACH', 'Cum suscipit quod est.', 'Ut dignissimos vero voluptas ea. Quia qui quasi quisquam quia. Maxime libero eum placeat sit sunt.', 221, '445', '142', '436', NULL, NULL, NULL),
(88, 10, 'SACH', 'Et maxime animi dolor.', 'Et exercitationem nobis esse. Iusto ex consequatur quam placeat consectetur maiores.', 327, '468', '480', '268', NULL, NULL, NULL),
(89, 8, 'SACH', 'Ipsa et et est est.', 'Voluptate error commodi rerum nihil at et. Magni at doloremque quae sint fugit eum fugit.', 404, '202', '494', '180', NULL, NULL, NULL),
(90, 6, 'SACH', 'Quos corrupti est quasi.', 'Aperiam aut non id inventore sapiente aut. Temporibus laudantium repudiandae deleniti magnam.', 239, '236', '226', '463', NULL, NULL, NULL),
(91, 3, 'SACH', 'Quis ducimus quis est.', 'Inventore voluptas sit est neque. Sit sed aut dolore voluptas omnis quasi.', 385, '468', '359', '407', NULL, NULL, NULL),
(92, 8, 'SACH', 'Id et ipsa excepturi.', 'Officiis optio sunt aliquid dolorem. Dolorem aut minus dolor quia.', 243, '218', '414', '450', NULL, NULL, NULL),
(93, 5, 'SACH', 'In saepe soluta magni.', 'Laudantium assumenda unde qui. Qui quia consequatur architecto officiis.', 426, '485', '339', '345', NULL, NULL, NULL),
(94, 7, 'SACH', 'Repellat id optio et et.', 'Vero ut eos et eveniet eum inventore id. Corporis accusamus fuga enim excepturi.', 258, '185', '347', '439', NULL, NULL, NULL),
(95, 7, 'SACH', 'Ad porro rerum ut.', 'Et ea labore ipsa delectus quia. Rerum non voluptatem illum cumque id facilis et.', 274, '432', '419', '463', NULL, NULL, NULL),
(96, 5, 'SACH', 'Ut sit in est.', 'Numquam quidem assumenda inventore rerum officiis aut. Repellat est quis dolores a pariatur quos.', 137, '299', '368', '129', NULL, NULL, NULL),
(97, 8, 'SACH', 'Atque sunt nam et.', 'Dolor voluptatem aut voluptates. Laudantium explicabo hic praesentium quaerat est totam.', 265, '126', '272', '363', NULL, NULL, NULL),
(98, 5, 'SACH', 'Unde placeat ut et quo.', 'Non ullam rerum inventore nihil enim. Id voluptatem aperiam quia modi.', 374, '208', '157', '208', NULL, NULL, NULL),
(99, 6, 'SACH', 'Distinctio qui et vitae.', 'Ut voluptatibus qui vel ea. Optio praesentium dolorem autem perspiciatis voluptatem officia in.', 424, '122', '360', '289', NULL, NULL, NULL),
(100, 8, 'SACH', 'Rerum est sed sit sunt.', 'Et sint ipsam eum rerum. Qui quia id earum numquam asperiores. Distinctio non nulla ex.', 397, '147', '231', '247', NULL, NULL, NULL),
(103, 14, 'SACH', 'Test', 'tesssst', 2000, '29', '21', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/4\",\"bia-chk-bia_cung\":true,\"ruot-in-so_trang\":\"78\",\"ruot-sel-loai_giay\":\"c150\",\"ruot-sel-mau_in\":\"4\\/4\",\"phu_ban-in-so_trang\":null,\"phu_ban-sel-loai_giay\":\"c150\",\"phu_ban-sel-mau_in\":\"3\\/3\",\"to_gac-in-so_trang\":null,\"to_gac-sel-loai_giay\":\"c150\",\"to_gac-sel-mau_in\":\"3\\/3\",\"checkSelected\":\"bia-mchk-cach_gia_cong-val-Aut dicta provident.,bia-mchk-cach_gia_cong-val-Provident dolorem.,bia-mchk-cach_gia_cong-val-Enim eaque.,gay-mchk-cach_gia_cong-val-Aut dicta provident.,gay-mchk-cach_gia_cong-val-Provident dolorem.,gay-mchk-cach_gia_cong-val-Enim eaque.\"}', NULL, NULL),
(108, 104, 'SACH', 'Sách', 's', 4000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c200\",\"bia-sel-mau_in\":\"4\\/4\",\"bia-chk-bia_cung\":false,\"ruot-in-so_trang\":\"84\",\"ruot-sel-loai_giay\":\"c50\",\"ruot-sel-mau_in\":\"4\\/4\",\"ruot-chk-cach_in\":false,\"phu_ban-sel-loai_giay\":\"c70\",\"phu_ban-sel-mau_in\":\"4\\/4\",\"to_gac-sel-loai_giay\":\"c70\",\"to_gac-sel-mau_in\":\"4\\/4\",\"checkSelected\":\"bia-mchk-cach_gia_cong-val-cach1,bia-mchk-cach_gia_cong-val-cach3,bia-mchk-cach_gia_cong-val-cach5,gay-mchk-cach_gia_cong-val-cach1,gay-mchk-cach_gia_cong-val-cach3,gay-mchk-cach_gia_cong-val-cach5\",\"gay-sel-cach_gia_cong\":\"phay_keo\"}', NULL, NULL),
(111, 104, 'SACH', 'Don 8135', NULL, 5000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/4\",\"bia-sel-cach_gia_cong\":\"cach1\",\"ruot-in-so_trang\":\"120\",\"ruot-sel-loai_giay\":\"c70\",\"ruot-sel-mau_in\":\"1\\/1\",\"gay-sel-cach_gia_cong\":\"phay_keo\",\"phu_ban-in-so_trang\":\"1\",\"phu_ban-sel-loai_giay\":\"c80\",\"phu_ban-sel-mau_in\":\"3\\/0\",\"to_gac-in-so_trang\":\"12\",\"to_gac-sel-loai_giay\":\"c150\",\"to_gac-sel-mau_in\":\"2\\/2\",\"checkSelected\":null}', NULL, NULL),
(112, 104, 'SACH', 'Don 8134', NULL, 30000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/4\",\"bia-sel-cach_gia_cong\":\"cach1\",\"ruot-in-so_trang\":\"84\",\"ruot-sel-loai_giay\":\"c70\",\"ruot-sel-mau_in\":\"4\\/4\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"phay_keo\",\"phu_ban-in-so_trang\":\"1\",\"phu_ban-sel-loai_giay\":\"c60\",\"phu_ban-sel-mau_in\":\"2\\/2\",\"to_gac-in-so_trang\":\"2\",\"to_gac-sel-loai_giay\":\"c150\",\"to_gac-sel-mau_in\":\"2\\/2\",\"checkSelected\":null}', NULL, NULL),
(113, 104, 'SACH', 'Don 8133', NULL, 3000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/4\",\"bia-sel-cach_gia_cong\":\"cach1\",\"ruot-in-so_trang\":\"180\",\"ruot-sel-loai_giay\":\"c50\",\"ruot-sel-mau_in\":\"1\\/1\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"phay_keo\",\"phu_ban-in-so_trang\":\"2\",\"phu_ban-sel-loai_giay\":\"c250\",\"phu_ban-sel-mau_in\":\"4\\/4\",\"to_gac-in-so_trang\":\"2\",\"to_gac-sel-loai_giay\":\"c150\",\"to_gac-sel-mau_in\":\"4\\/4\",\"checkSelected\":null}', NULL, NULL),
(114, 104, 'SACH', 'Don 8069', NULL, 10000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c250\",\"bia-sel-mau_in\":\"4\\/0\",\"bia-sel-cach_gia_cong\":\"cach4\",\"ruot-in-so_trang\":\"132\",\"ruot-sel-loai_giay\":\"c50\",\"ruot-sel-mau_in\":\"2\\/2\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"khau_chi\",\"phu_ban-in-so_trang\":\"12\",\"phu_ban-sel-loai_giay\":\"c80\",\"phu_ban-sel-mau_in\":\"4\\/4\",\"checkSelected\":null}', NULL, NULL),
(115, 104, 'SACH', 'ABC01', NULL, 10000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/0\",\"bia-sel-cach_gia_cong\":\"cach4\",\"ruot-in-so_trang\":\"180\",\"ruot-sel-loai_giay\":\"c70\",\"ruot-sel-mau_in\":\"4\\/4\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"phay_keo\",\"phu_ban-in-so_trang\":null,\"checkSelected\":null}', NULL, NULL),
(116, 104, 'SACH', '8069 nam con 30 05', NULL, 10000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/0\",\"bia-sel-cach_gia_cong\":\"cach5\",\"ruot-in-so_trang\":\"76\",\"ruot-sel-loai_giay\":\"c70\",\"ruot-sel-mau_in\":\"1\\/1\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"khau_chi\",\"checkSelected\":null}', NULL, NULL),
(117, 104, 'SACH', '8071', NULL, 6000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/0\",\"bia-sel-cach_gia_cong\":\"cach3\",\"ruot-in-so_trang\":\"28\",\"ruot-sel-loai_giay\":\"c70\",\"ruot-sel-mau_in\":\"2\\/2\",\"gay-sel-cach_gia_cong\":\"khau_chi\",\"checkSelected\":null}', NULL, NULL),
(118, 104, 'SACH', 'Sach 180 trang', NULL, 20000, '24', '17', NULL, '{\"bia-sel-loai_giay\":\"c150\",\"bia-sel-mau_in\":\"4\\/0\",\"bia-sel-cach_gia_cong\":\"cach3\",\"ruot-in-so_trang\":\"120\",\"ruot-sel-loai_giay\":\"c50\",\"ruot-sel-mau_in\":\"1\\/1\",\"ruot-chk-cach_in\":true,\"gay-sel-cach_gia_cong\":\"phay_keo\",\"checkSelected\":null}', NULL, NULL);
";
        // echo $sql;exit;
        DB::unprepared($sql);
    }
}
